# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.IntegerField(null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('yofstudy', models.CharField(max_length=255)),
                ('nop', models.IntegerField(default=0)),
                ('un', models.CharField(default='core', max_length=255)),
                ('pw', models.CharField(default='core@xyz', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
